DELETE FROM etf_holdings
WHERE etf_id IN (
  SELECT id FROM etfs WHERE ticker IN ('IUSQ','EEMA','VGVF','ICOM','SPYD','EXXY','IUSN','NUKL','CBUK','CQQQ','XDWT')
);

DELETE FROM etf_exposures
WHERE etf_id IN (
  SELECT id FROM etfs WHERE ticker IN ('IUSQ','EEMA','VGVF','ICOM','SPYD','EXXY','IUSN','NUKL','CBUK','CQQQ','XDWT')
);

INSERT INTO etf_exposures (id, created_at, updated_at, etf_id, type, name, weight)
SELECT gen_random_uuid(), now(), now(), e.id, x.type::varchar(40), x.name, x.weight
FROM etfs e
JOIN (VALUES
  ('IUSQ','ASSET_CLASS','Equity',100.0),
  ('IUSQ','SECTOR','Technology',24.0),('IUSQ','SECTOR','Financial Services',16.0),('IUSQ','SECTOR','Healthcare',12.0),('IUSQ','SECTOR','Consumer Cyclical',11.0),('IUSQ','SECTOR','Industrials',10.0),('IUSQ','SECTOR','Communication Services',8.0),('IUSQ','SECTOR','Consumer Defensive',7.0),('IUSQ','SECTOR','Energy',4.0),('IUSQ','SECTOR','Utilities',3.0),('IUSQ','SECTOR','Basic Materials',3.0),('IUSQ','SECTOR','Real Estate',2.0),
  ('IUSQ','INDUSTRY','Software',12.0),('IUSQ','INDUSTRY','Semiconductors',11.0),('IUSQ','INDUSTRY','Consumer Electronics',8.0),('IUSQ','INDUSTRY','Internet Retail',7.0),('IUSQ','INDUSTRY','Banks',8.0),('IUSQ','INDUSTRY','Insurance',5.0),('IUSQ','INDUSTRY','Pharmaceuticals',7.0),('IUSQ','INDUSTRY','Capital Markets',5.0),('IUSQ','INDUSTRY','Industrial Machinery',6.0),('IUSQ','INDUSTRY','Oil and Gas',5.0),('IUSQ','INDUSTRY','Utilities',4.0),('IUSQ','INDUSTRY','Consumer Staples',7.0),('IUSQ','INDUSTRY','Real Estate',5.0),('IUSQ','INDUSTRY','Materials',4.0),('IUSQ','INDUSTRY','Aerospace and Defense',4.0),('IUSQ','INDUSTRY','Electrical Equipment',2.0),
  ('IUSQ','COUNTRY','United States',58.0),('IUSQ','COUNTRY','Japan',6.0),('IUSQ','COUNTRY','United Kingdom',4.0),('IUSQ','COUNTRY','Switzerland',3.0),('IUSQ','COUNTRY','France',3.0),('IUSQ','COUNTRY','Germany',3.0),('IUSQ','COUNTRY','Canada',3.0),('IUSQ','COUNTRY','Taiwan',3.0),('IUSQ','COUNTRY','India',2.0),('IUSQ','COUNTRY','China',2.0),('IUSQ','COUNTRY','Netherlands',2.0),('IUSQ','COUNTRY','Australia',2.0),('IUSQ','COUNTRY','South Korea',2.0),('IUSQ','COUNTRY','Denmark',1.0),('IUSQ','COUNTRY','Sweden',1.0),('IUSQ','COUNTRY','Spain',1.0),('IUSQ','COUNTRY','Italy',1.0),('IUSQ','COUNTRY','Brazil',1.0),('IUSQ','COUNTRY','Saudi Arabia',1.0),('IUSQ','COUNTRY','South Africa',1.0),

  ('EEMA','ASSET_CLASS','Equity',100.0),
  ('EEMA','SECTOR','Technology',25.0),('EEMA','SECTOR','Financial Services',20.0),('EEMA','SECTOR','Consumer Cyclical',14.0),('EEMA','SECTOR','Communication Services',10.0),('EEMA','SECTOR','Industrials',7.0),('EEMA','SECTOR','Healthcare',6.0),('EEMA','SECTOR','Energy',5.0),('EEMA','SECTOR','Basic Materials',4.0),('EEMA','SECTOR','Consumer Defensive',4.0),('EEMA','SECTOR','Real Estate',3.0),('EEMA','SECTOR','Utilities',2.0),
  ('EEMA','INDUSTRY','Semiconductors',15.0),('EEMA','INDUSTRY','Banks',11.0),('EEMA','INDUSTRY','Internet Retail',9.0),('EEMA','INDUSTRY','Software',7.0),('EEMA','INDUSTRY','Insurance',5.0),('EEMA','INDUSTRY','Consumer Electronics',6.0),('EEMA','INDUSTRY','Internet Content',8.0),('EEMA','INDUSTRY','Oil and Gas',5.0),('EEMA','INDUSTRY','Capital Markets',5.0),('EEMA','INDUSTRY','Telecom Services',5.0),('EEMA','INDUSTRY','Electrical Equipment',4.0),('EEMA','INDUSTRY','Industrial Machinery',4.0),('EEMA','INDUSTRY','Pharmaceuticals',4.0),('EEMA','INDUSTRY','Materials',4.0),('EEMA','INDUSTRY','Auto Manufacturers',3.0),
  ('EEMA','COUNTRY','China',28.0),('EEMA','COUNTRY','India',23.0),('EEMA','COUNTRY','Taiwan',21.0),('EEMA','COUNTRY','South Korea',14.0),('EEMA','COUNTRY','Indonesia',3.0),('EEMA','COUNTRY','Thailand',3.0),('EEMA','COUNTRY','Malaysia',3.0),('EEMA','COUNTRY','Saudi Arabia',3.0),('EEMA','COUNTRY','Philippines',2.0),

  ('VGVF','ASSET_CLASS','Equity',100.0),
  ('VGVF','SECTOR','Technology',26.0),('VGVF','SECTOR','Financial Services',14.0),('VGVF','SECTOR','Healthcare',13.0),('VGVF','SECTOR','Industrials',11.0),('VGVF','SECTOR','Consumer Cyclical',10.0),('VGVF','SECTOR','Communication Services',8.0),('VGVF','SECTOR','Consumer Defensive',7.0),('VGVF','SECTOR','Energy',4.0),('VGVF','SECTOR','Basic Materials',3.0),('VGVF','SECTOR','Real Estate',2.0),('VGVF','SECTOR','Utilities',2.0),
  ('VGVF','INDUSTRY','Software',14.0),('VGVF','INDUSTRY','Semiconductors',11.0),('VGVF','INDUSTRY','Consumer Electronics',8.0),('VGVF','INDUSTRY','Banks',7.0),('VGVF','INDUSTRY','Insurance',5.0),('VGVF','INDUSTRY','Pharmaceuticals',8.0),('VGVF','INDUSTRY','Capital Markets',5.0),('VGVF','INDUSTRY','Industrial Machinery',6.0),('VGVF','INDUSTRY','Oil and Gas',6.0),('VGVF','INDUSTRY','Consumer Staples',8.0),('VGVF','INDUSTRY','Real Estate',5.0),('VGVF','INDUSTRY','Materials',4.0),('VGVF','INDUSTRY','Aerospace and Defense',4.0),('VGVF','INDUSTRY','Electrical Equipment',3.0),('VGVF','INDUSTRY','Internet Retail',4.0),('VGVF','INDUSTRY','Information Technology Services',2.0),
  ('VGVF','COUNTRY','United States',69.0),('VGVF','COUNTRY','Japan',6.5),('VGVF','COUNTRY','United Kingdom',4.5),('VGVF','COUNTRY','Switzerland',3.0),('VGVF','COUNTRY','France',3.0),('VGVF','COUNTRY','Germany',3.0),('VGVF','COUNTRY','Canada',3.0),('VGVF','COUNTRY','Netherlands',2.0),('VGVF','COUNTRY','Australia',2.0),('VGVF','COUNTRY','Denmark',1.0),('VGVF','COUNTRY','Sweden',1.0),('VGVF','COUNTRY','Spain',1.0),('VGVF','COUNTRY','Italy',1.0),

  ('ICOM','ASSET_CLASS','Commodities',100.0),
  ('ICOM','SECTOR','Energy Commodities',34.0),('ICOM','SECTOR','Agriculture',28.0),('ICOM','SECTOR','Industrial Metals',18.0),('ICOM','SECTOR','Precious Metals',16.0),('ICOM','SECTOR','Livestock',4.0),
  ('ICOM','INDUSTRY','Oil and Gas Futures',25.0),('ICOM','INDUSTRY','Grains',16.0),('ICOM','INDUSTRY','Gold',11.0),('ICOM','INDUSTRY','Copper',8.0),('ICOM','INDUSTRY','Natural Gas',7.0),('ICOM','INDUSTRY','Silver',6.0),('ICOM','INDUSTRY','Soybeans',5.0),('ICOM','INDUSTRY','Aluminum',4.0),('ICOM','INDUSTRY','Livestock',4.0),('ICOM','INDUSTRY','Coffee',3.0),('ICOM','INDUSTRY','Sugar',3.0),('ICOM','INDUSTRY','Wheat',4.0),('ICOM','INDUSTRY','Cocoa',2.0),('ICOM','INDUSTRY','Nickel',2.0),
  ('ICOM','COUNTRY','Global',100.0),

  ('SPYD','ASSET_CLASS','Equity',100.0),
  ('SPYD','SECTOR','Financial Services',20.0),('SPYD','SECTOR','Industrials',16.0),('SPYD','SECTOR','Consumer Defensive',14.0),('SPYD','SECTOR','Healthcare',11.0),('SPYD','SECTOR','Energy',10.0),('SPYD','SECTOR','Real Estate',9.0),('SPYD','SECTOR','Utilities',8.0),('SPYD','SECTOR','Communication Services',5.0),('SPYD','SECTOR','Basic Materials',4.0),('SPYD','SECTOR','Technology',3.0),
  ('SPYD','INDUSTRY','REITs',14.0),('SPYD','INDUSTRY','Banks',13.0),('SPYD','INDUSTRY','Utilities Regulated',11.0),('SPYD','INDUSTRY','Oil and Gas',10.0),('SPYD','INDUSTRY','Food Products',8.0),('SPYD','INDUSTRY','Insurance',7.0),('SPYD','INDUSTRY','Telecom Services',7.0),('SPYD','INDUSTRY','Capital Markets',6.0),('SPYD','INDUSTRY','Household Products',5.0),('SPYD','INDUSTRY','Pharmaceuticals',5.0),('SPYD','INDUSTRY','Beverages',4.0),('SPYD','INDUSTRY','Aerospace and Defense',3.0),('SPYD','INDUSTRY','Industrial Conglomerates',3.0),('SPYD','INDUSTRY','Real Estate Services',2.0),('SPYD','INDUSTRY','Materials',2.0),
  ('SPYD','COUNTRY','United States',100.0),

  ('EXXY','ASSET_CLASS','Equity',100.0),
  ('EXXY','SECTOR','Financial Services',18.0),('EXXY','SECTOR','Industrials',17.0),('EXXY','SECTOR','Healthcare',15.0),('EXXY','SECTOR','Consumer Defensive',11.0),('EXXY','SECTOR','Technology',10.0),('EXXY','SECTOR','Energy',8.0),('EXXY','SECTOR','Basic Materials',7.0),('EXXY','SECTOR','Utilities',5.0),('EXXY','SECTOR','Consumer Cyclical',4.0),('EXXY','SECTOR','Communication Services',3.0),('EXXY','SECTOR','Real Estate',2.0),
  ('EXXY','INDUSTRY','Banks',12.0),('EXXY','INDUSTRY','Pharmaceuticals',11.0),('EXXY','INDUSTRY','Insurance',9.0),('EXXY','INDUSTRY','Specialty Chemicals',7.0),('EXXY','INDUSTRY','Industrial Machinery',7.0),('EXXY','INDUSTRY','Semiconductors',6.0),('EXXY','INDUSTRY','Software',6.0),('EXXY','INDUSTRY','Oil and Gas',7.0),('EXXY','INDUSTRY','Consumer Staples',8.0),('EXXY','INDUSTRY','Aerospace and Defense',4.0),('EXXY','INDUSTRY','Capital Markets',5.0),('EXXY','INDUSTRY','Utilities',5.0),('EXXY','INDUSTRY','Household Products',5.0),('EXXY','INDUSTRY','Beverages',4.0),('EXXY','INDUSTRY','Telecom Services',4.0),
  ('EXXY','COUNTRY','United Kingdom',18.0),('EXXY','COUNTRY','Switzerland',14.0),('EXXY','COUNTRY','France',12.0),('EXXY','COUNTRY','Germany',12.0),('EXXY','COUNTRY','Netherlands',10.0),('EXXY','COUNTRY','Spain',8.0),('EXXY','COUNTRY','Italy',7.0),('EXXY','COUNTRY','Denmark',5.0),('EXXY','COUNTRY','Sweden',5.0),('EXXY','COUNTRY','Belgium',4.0),('EXXY','COUNTRY','Finland',3.0),('EXXY','COUNTRY','Ireland',2.0),

  ('IUSN','ASSET_CLASS','Equity',100.0),
  ('IUSN','SECTOR','Industrials',18.0),('IUSN','SECTOR','Financial Services',15.0),('IUSN','SECTOR','Technology',15.0),('IUSN','SECTOR','Healthcare',12.0),('IUSN','SECTOR','Consumer Cyclical',11.0),('IUSN','SECTOR','Real Estate',8.0),('IUSN','SECTOR','Basic Materials',7.0),('IUSN','SECTOR','Communication Services',4.0),('IUSN','SECTOR','Consumer Defensive',4.0),('IUSN','SECTOR','Energy',4.0),('IUSN','SECTOR','Utilities',2.0),
  ('IUSN','INDUSTRY','Industrial Machinery',14.0),('IUSN','INDUSTRY','Software',9.0),('IUSN','INDUSTRY','Banks',8.0),('IUSN','INDUSTRY','Medical Devices',8.0),('IUSN','INDUSTRY','Specialty Retail',7.0),('IUSN','INDUSTRY','Electrical Equipment',7.0),('IUSN','INDUSTRY','Aerospace and Defense',6.0),('IUSN','INDUSTRY','Capital Markets',6.0),('IUSN','INDUSTRY','REITs',6.0),('IUSN','INDUSTRY','Oil and Gas Equipment',5.0),('IUSN','INDUSTRY','Business Services',5.0),('IUSN','INDUSTRY','Semiconductors',5.0),('IUSN','INDUSTRY','Utilities Regulated',5.0),('IUSN','INDUSTRY','Materials',4.0),('IUSN','INDUSTRY','Insurance',5.0),
  ('IUSN','COUNTRY','United States',58.0),('IUSN','COUNTRY','Japan',10.0),('IUSN','COUNTRY','United Kingdom',7.0),('IUSN','COUNTRY','Canada',5.0),('IUSN','COUNTRY','Sweden',3.0),('IUSN','COUNTRY','Switzerland',3.0),('IUSN','COUNTRY','Australia',3.0),('IUSN','COUNTRY','Germany',3.0),('IUSN','COUNTRY','France',2.0),('IUSN','COUNTRY','Italy',2.0),('IUSN','COUNTRY','Netherlands',2.0),('IUSN','COUNTRY','Israel',2.0),

  ('NUKL','ASSET_CLASS','Equity',100.0),
  ('NUKL','SECTOR','Energy',35.0),('NUKL','SECTOR','Industrials',22.0),('NUKL','SECTOR','Utilities',18.0),('NUKL','SECTOR','Basic Materials',15.0),('NUKL','SECTOR','Technology',5.0),('NUKL','SECTOR','Financial Services',3.0),('NUKL','SECTOR','Communication Services',2.0),
  ('NUKL','INDUSTRY','Uranium',28.0),('NUKL','INDUSTRY','Electrical Equipment',18.0),('NUKL','INDUSTRY','Renewable Utilities',14.0),('NUKL','INDUSTRY','Engineering and Construction',10.0),('NUKL','INDUSTRY','Industrial Machinery',8.0),('NUKL','INDUSTRY','Oil and Gas Services',6.0),('NUKL','INDUSTRY','Aerospace and Defense',5.0),('NUKL','INDUSTRY','Materials',4.0),('NUKL','INDUSTRY','Semiconductors',4.0),('NUKL','INDUSTRY','Capital Markets',3.0),
  ('NUKL','COUNTRY','Canada',24.0),('NUKL','COUNTRY','United States',23.0),('NUKL','COUNTRY','Kazakhstan',13.0),('NUKL','COUNTRY','South Korea',8.0),('NUKL','COUNTRY','Japan',7.0),('NUKL','COUNTRY','France',5.0),('NUKL','COUNTRY','Germany',5.0),('NUKL','COUNTRY','United Kingdom',4.0),('NUKL','COUNTRY','Australia',4.0),('NUKL','COUNTRY','Netherlands',3.0),('NUKL','COUNTRY','Italy',2.0),('NUKL','COUNTRY','Sweden',2.0),

  ('CBUK','ASSET_CLASS','Equity',100.0),
  ('CBUK','SECTOR','Financial Services',20.0),('CBUK','SECTOR','Consumer Defensive',17.0),('CBUK','SECTOR','Healthcare',13.0),('CBUK','SECTOR','Energy',12.0),('CBUK','SECTOR','Basic Materials',10.0),('CBUK','SECTOR','Industrials',8.0),('CBUK','SECTOR','Communication Services',6.0),('CBUK','SECTOR','Utilities',5.0),('CBUK','SECTOR','Consumer Cyclical',4.0),('CBUK','SECTOR','Real Estate',3.0),('CBUK','SECTOR','Technology',2.0),
  ('CBUK','INDUSTRY','Banks',12.0),('CBUK','INDUSTRY','Oil and Gas',12.0),('CBUK','INDUSTRY','Pharmaceuticals',11.0),('CBUK','INDUSTRY','Beverages',9.0),('CBUK','INDUSTRY','Mining',7.0),('CBUK','INDUSTRY','Insurance',7.0),('CBUK','INDUSTRY','Consumer Staples',7.0),('CBUK','INDUSTRY','Utilities',6.0),('CBUK','INDUSTRY','Aerospace and Defense',5.0),('CBUK','INDUSTRY','Telecom Services',5.0),('CBUK','INDUSTRY','Household Products',5.0),('CBUK','INDUSTRY','Capital Markets',4.0),('CBUK','INDUSTRY','REITs',4.0),('CBUK','INDUSTRY','Materials',3.0),('CBUK','INDUSTRY','Retail',3.0),
  ('CBUK','COUNTRY','United Kingdom',100.0),

  ('CQQQ','ASSET_CLASS','Equity',100.0),
  ('CQQQ','SECTOR','Technology',42.0),('CQQQ','SECTOR','Communication Services',25.0),('CQQQ','SECTOR','Consumer Cyclical',18.0),('CQQQ','SECTOR','Industrials',6.0),('CQQQ','SECTOR','Financial Services',4.0),('CQQQ','SECTOR','Healthcare',3.0),('CQQQ','SECTOR','Real Estate',2.0),
  ('CQQQ','INDUSTRY','Internet Content',20.0),('CQQQ','INDUSTRY','Internet Retail',19.0),('CQQQ','INDUSTRY','Software',14.0),('CQQQ','INDUSTRY','Semiconductors',11.0),('CQQQ','INDUSTRY','Electronic Components',8.0),('CQQQ','INDUSTRY','Consumer Electronics',7.0),('CQQQ','INDUSTRY','Telecom Services',6.0),('CQQQ','INDUSTRY','Capital Markets',4.0),('CQQQ','INDUSTRY','Real Estate Development',3.0),('CQQQ','INDUSTRY','Travel Services',3.0),('CQQQ','INDUSTRY','Healthcare Services',2.0),('CQQQ','INDUSTRY','Electrical Equipment',3.0),
  ('CQQQ','COUNTRY','China',88.0),('CQQQ','COUNTRY','Taiwan',4.0),('CQQQ','COUNTRY','United States',3.0),('CQQQ','COUNTRY','Hong Kong',3.0),('CQQQ','COUNTRY','Singapore',2.0),

  ('XDWT','ASSET_CLASS','Equity',100.0),
  ('XDWT','SECTOR','Technology',100.0),
  ('XDWT','INDUSTRY','Semiconductors',32.0),('XDWT','INDUSTRY','Software',27.0),('XDWT','INDUSTRY','Consumer Electronics',14.0),('XDWT','INDUSTRY','Information Technology Services',10.0),('XDWT','INDUSTRY','Semiconductor Equipment',7.0),('XDWT','INDUSTRY','Electronic Components',10.0),
  ('XDWT','COUNTRY','United States',84.0),('XDWT','COUNTRY','Taiwan',4.0),('XDWT','COUNTRY','Netherlands',4.0),('XDWT','COUNTRY','Japan',3.0),('XDWT','COUNTRY','South Korea',2.0),('XDWT','COUNTRY','Germany',1.0),('XDWT','COUNTRY','France',1.0),('XDWT','COUNTRY','Switzerland',1.0)
) AS x(ticker, type, name, weight) ON x.ticker = e.ticker;

INSERT INTO etf_holdings (id, created_at, updated_at, etf_id, symbol, name, country, sector, industry, weight)
SELECT gen_random_uuid(), now(), now(), e.id, x.symbol, x.name, x.country, x.sector, x.industry, x.weight
FROM etfs e
JOIN (VALUES
  ('IUSQ','AAPL','Apple','United States','Technology','Consumer Electronics',4.4),('IUSQ','MSFT','Microsoft','United States','Technology','Software',4.1),('IUSQ','NVDA','NVIDIA','United States','Technology','Semiconductors',3.5),('IUSQ','AMZN','Amazon','United States','Consumer Cyclical','Internet Retail',2.2),('IUSQ','TSM','Taiwan Semiconductor','Taiwan','Technology','Semiconductors',1.4),('IUSQ','META','Meta Platforms','United States','Communication Services','Internet Content',1.2),('IUSQ','GOOGL','Alphabet','United States','Communication Services','Internet Content',1.2),('IUSQ','JPM','JPMorgan Chase','United States','Financial Services','Banks',1.0),('IUSQ','LLY','Eli Lilly','United States','Healthcare','Pharmaceuticals',1.0),('IUSQ','AVGO','Broadcom','United States','Technology','Semiconductors',0.9),('IUSQ','ASML','ASML','Netherlands','Technology','Semiconductor Equipment',0.8),('IUSQ','NESN','Nestle','Switzerland','Consumer Defensive','Consumer Staples',0.7),('IUSQ','NOVN','Novartis','Switzerland','Healthcare','Pharmaceuticals',0.7),('IUSQ','XOM','Exxon Mobil','United States','Energy','Oil and Gas',0.7),('IUSQ','V','Visa','United States','Financial Services','Capital Markets',0.6),('IUSQ','SAP','SAP','Germany','Technology','Software',0.6),('IUSQ','ORCL','Oracle','United States','Technology','Software',0.5),('IUSQ','COST','Costco','United States','Consumer Defensive','Consumer Staples',0.5),('IUSQ','BABA','Alibaba','China','Consumer Cyclical','Internet Retail',0.5),('IUSQ','RELIANCE','Reliance Industries','India','Energy','Oil and Gas',0.5),

  ('EEMA','TSM','Taiwan Semiconductor','Taiwan','Technology','Semiconductors',8.2),('EEMA','TCEHY','Tencent','China','Communication Services','Internet Content',4.4),('EEMA','SAMSUNG','Samsung Electronics','South Korea','Technology','Consumer Electronics',3.5),('EEMA','BABA','Alibaba','China','Consumer Cyclical','Internet Retail',3.1),('EEMA','RELIANCE','Reliance Industries','India','Energy','Oil and Gas',2.4),('EEMA','ICICIBANK','ICICI Bank','India','Financial Services','Banks',2.2),('EEMA','HDFCBANK','HDFC Bank','India','Financial Services','Banks',2.1),('EEMA','MEDIATEK','MediaTek','Taiwan','Technology','Semiconductors',1.8),('EEMA','XIAOMI','Xiaomi','China','Technology','Consumer Electronics',1.7),('EEMA','MEITUAN','Meituan','China','Consumer Cyclical','Internet Retail',1.6),('EEMA','INFY','Infosys','India','Technology','Software',1.2),('EEMA','SKHYNIX','SK Hynix','South Korea','Technology','Semiconductors',1.8),('EEMA','ALIBANK','Al Rajhi Bank','Saudi Arabia','Financial Services','Banks',1.5),('EEMA','PDD','PDD Holdings','China','Consumer Cyclical','Internet Retail',1.5),('EEMA','PETROCHINA','PetroChina','China','Energy','Oil and Gas',1.2),

  ('VGVF','AAPL','Apple','United States','Technology','Consumer Electronics',5.0),('VGVF','MSFT','Microsoft','United States','Technology','Software',4.8),('VGVF','NVDA','NVIDIA','United States','Technology','Semiconductors',4.0),('VGVF','NOVN','Novartis','Switzerland','Healthcare','Pharmaceuticals',1.1),('VGVF','ASML','ASML','Netherlands','Technology','Semiconductor Equipment',1.0),('VGVF','SAP','SAP','Germany','Technology','Software',0.9),('VGVF','SHEL','Shell','United Kingdom','Energy','Oil and Gas',0.8),('VGVF','HSBA','HSBC','United Kingdom','Financial Services','Banks',0.8),('VGVF','NESN','Nestle','Switzerland','Consumer Defensive','Consumer Staples',0.8),('VGVF','AZN','AstraZeneca','United Kingdom','Healthcare','Pharmaceuticals',0.8),('VGVF','RY','Royal Bank of Canada','Canada','Financial Services','Banks',0.7),('VGVF','SONY','Sony','Japan','Technology','Consumer Electronics',0.7),('VGVF','SU','Schneider Electric','France','Industrials','Electrical Equipment',0.6),('VGVF','RELX','RELX','United Kingdom','Communication Services','Business Services',0.6),('VGVF','AIR','Airbus','France','Industrials','Aerospace and Defense',0.5),('VGVF','UL','Unilever','United Kingdom','Consumer Defensive','Consumer Staples',0.5),('VGVF','BHP','BHP Group','Australia','Basic Materials','Materials',0.5),('VGVF','TOTAL','TotalEnergies','France','Energy','Oil and Gas',0.5),('VGVF','SAN','Sanofi','France','Healthcare','Pharmaceuticals',0.5),('VGVF','UBS','UBS','Switzerland','Financial Services','Capital Markets',0.5),

  ('ICOM','WTI','WTI Crude Oil Futures','Global','Energy Commodities','Oil and Gas Futures',10.0),('ICOM','GOLD','Gold Futures','Global','Precious Metals','Gold',11.0),('ICOM','COPPER','Copper Futures','Global','Industrial Metals','Copper',8.0),('ICOM','NG','Natural Gas Futures','Global','Energy Commodities','Natural Gas',7.0),('ICOM','CORN','Corn Futures','Global','Agriculture','Grains',5.0),('ICOM','SILVER','Silver Futures','Global','Precious Metals','Silver',4.5),('ICOM','SOY','Soybean Futures','Global','Agriculture','Soybeans',4.0),('ICOM','ALUM','Aluminum Futures','Global','Industrial Metals','Aluminum',3.0),('ICOM','WHEAT','Wheat Futures','Global','Agriculture','Wheat',3.0),('ICOM','SUGAR','Sugar Futures','Global','Agriculture','Sugar',2.5),('ICOM','COFFEE','Coffee Futures','Global','Agriculture','Coffee',1.5),('ICOM','LIVESTOCK','Live Cattle Futures','Global','Livestock','Livestock',1.5),

  ('SPYD','XOM','Exxon Mobil','United States','Energy','Oil and Gas',2.5),('SPYD','T','AT&T','United States','Communication Services','Telecom Services',2.2),('SPYD','O','Realty Income','United States','Real Estate','REITs',2.0),('SPYD','IBM','IBM','United States','Technology','Information Technology Services',1.8),('SPYD','KO','Coca-Cola','United States','Consumer Defensive','Beverages',1.7),('SPYD','CVX','Chevron','United States','Energy','Oil and Gas',1.7),('SPYD','KMI','Kinder Morgan','United States','Energy','Oil and Gas',1.6),('SPYD','USB','US Bancorp','United States','Financial Services','Banks',1.5),('SPYD','PRU','Prudential Financial','United States','Financial Services','Insurance',1.5),('SPYD','DOW','Dow','United States','Basic Materials','Materials',1.4),('SPYD','OMC','Omnicom','United States','Communication Services','Business Services',1.3),('SPYD','VZ','Verizon','United States','Communication Services','Telecom Services',1.3),

  ('EXXY','NESN','Nestle','Switzerland','Consumer Defensive','Consumer Staples',3.2),('EXXY','ASML','ASML','Netherlands','Technology','Semiconductors',2.8),('EXXY','NOVN','Novartis','Switzerland','Healthcare','Pharmaceuticals',2.4),('EXXY','SAP','SAP','Germany','Technology','Software',2.1),('EXXY','SHEL','Shell','United Kingdom','Energy','Oil and Gas',2.0),('EXXY','ROG','Roche','Switzerland','Healthcare','Pharmaceuticals',1.9),('EXXY','HSBA','HSBC','United Kingdom','Financial Services','Banks',1.8),('EXXY','ULVR','Unilever','United Kingdom','Consumer Defensive','Household Products',1.7),('EXXY','AIR','Airbus','France','Industrials','Aerospace and Defense',1.6),('EXXY','SIE','Siemens','Germany','Industrials','Industrial Machinery',1.5),('EXXY','INGA','ING','Netherlands','Financial Services','Banks',1.4),('EXXY','BNP','BNP Paribas','France','Financial Services','Banks',1.4),('EXXY','OR','L''Oreal','France','Consumer Defensive','Consumer Staples',1.3),('EXXY','IBE','Iberdrola','Spain','Utilities','Utilities',1.2),('EXXY','BAS','BASF','Germany','Basic Materials','Specialty Chemicals',1.2),

  ('IUSN','SMCI','Super Micro Computer','United States','Technology','Computer Hardware',0.35),('IUSN','FIX','Comfort Systems','United States','Industrials','Engineering and Construction',0.30),('IUSN','SAAB','Saab','Sweden','Industrials','Aerospace and Defense',0.25),('IUSN','FN','Fabrinet','United States','Technology','Electronic Components',0.24),('IUSN','RBC','RBC Bearings','United States','Industrials','Industrial Machinery',0.22),('IUSN','AXON','Axon Enterprise','United States','Industrials','Aerospace and Defense',0.60),('IUSN','EME','EMCOR','United States','Industrials','Engineering and Construction',0.55),('IUSN','PINS','Pinterest','United States','Communication Services','Internet Content',0.52),('IUSN','OWL','Blue Owl Capital','United States','Financial Services','Capital Markets',0.50),('IUSN','CAR','Avis Budget Group','United States','Consumer Cyclical','Specialty Retail',0.48),('IUSN','DT','Dynatrace','United States','Technology','Software',0.46),('IUSN','JHX','James Hardie','Australia','Basic Materials','Materials',0.44),('IUSN','MTZ','MasTec','United States','Industrials','Engineering and Construction',0.42),('IUSN','RNR','RenaissanceRe','Bermuda','Financial Services','Insurance',0.40),('IUSN','DOC','Healthpeak Properties','United States','Real Estate','REITs',0.38),

  ('NUKL','CCJ','Cameco','Canada','Energy','Uranium',12.0),('NUKL','KAP','Kazatomprom','Kazakhstan','Energy','Uranium',9.5),('NUKL','CEG','Constellation Energy','United States','Utilities','Renewable Utilities',8.0),('NUKL','BWXT','BWX Technologies','United States','Industrials','Aerospace and Defense',6.5),('NUKL','UEC','Uranium Energy','United States','Energy','Uranium',4.5),('NUKL','SMR','NuScale Power','United States','Industrials','Engineering and Construction',3.4),('NUKL','GEV','GE Vernova','United States','Industrials','Electrical Equipment',3.2),('NUKL','ORANO','Orano','France','Basic Materials','Uranium',3.0),('NUKL','MITS','Mitsubishi Heavy Industries','Japan','Industrials','Industrial Machinery',2.6),('NUKL','KOREAEP','Korea Electric Power','South Korea','Utilities','Utilities',2.4),

  ('CBUK','AZN','AstraZeneca','United Kingdom','Healthcare','Pharmaceuticals',8.0),('CBUK','SHEL','Shell','United Kingdom','Energy','Oil and Gas',7.5),('CBUK','HSBA','HSBC','United Kingdom','Financial Services','Banks',6.2),('CBUK','ULVR','Unilever','United Kingdom','Consumer Defensive','Household Products',5.0),('CBUK','BP','BP','United Kingdom','Energy','Oil and Gas',4.2),('CBUK','DGE','Diageo','United Kingdom','Consumer Defensive','Beverages',4.0),('CBUK','RIO','Rio Tinto','United Kingdom','Basic Materials','Mining',3.8),('CBUK','BA','BAE Systems','United Kingdom','Industrials','Aerospace and Defense',3.5),('CBUK','GSK','GSK','United Kingdom','Healthcare','Pharmaceuticals',3.4),('CBUK','VOD','Vodafone','United Kingdom','Communication Services','Telecom Services',3.2),('CBUK','LGEN','Legal & General','United Kingdom','Financial Services','Insurance',3.0),('CBUK','LAND','Land Securities','United Kingdom','Real Estate','REITs',2.8),

  ('CQQQ','TCEHY','Tencent','China','Communication Services','Internet Content',10.0),('CQQQ','BABA','Alibaba','China','Consumer Cyclical','Internet Retail',8.0),('CQQQ','JD','JD.com','China','Consumer Cyclical','Internet Retail',5.0),('CQQQ','BIDU','Baidu','China','Communication Services','Internet Content',4.0),('CQQQ','XIAOMI','Xiaomi','China','Technology','Consumer Electronics',4.0),('CQQQ','PDD','PDD Holdings','China','Consumer Cyclical','Internet Retail',4.0),('CQQQ','NTES','NetEase','China','Communication Services','Internet Content',3.0),('CQQQ','BYD','BYD','China','Industrials','Electrical Equipment',3.0),('CQQQ','SMIC','SMIC','China','Technology','Semiconductors',2.0),('CQQQ','TRIP','Trip.com','China','Consumer Cyclical','Travel Services',2.0),('CQQQ','MEITUAN','Meituan','China','Consumer Cyclical','Internet Retail',4.0),

  ('XDWT','AAPL','Apple','United States','Technology','Consumer Electronics',18.0),('XDWT','MSFT','Microsoft','United States','Technology','Software',17.0),('XDWT','NVDA','NVIDIA','United States','Technology','Semiconductors',14.0),('XDWT','AVGO','Broadcom','United States','Technology','Semiconductors',5.8),('XDWT','ASML','ASML','Netherlands','Technology','Semiconductor Equipment',3.2),('XDWT','TSM','Taiwan Semiconductor','Taiwan','Technology','Semiconductors',4.0),('XDWT','AMD','AMD','United States','Technology','Semiconductors',2.5),('XDWT','CRM','Salesforce','United States','Technology','Software',2.3),('XDWT','ORCL','Oracle','United States','Technology','Software',1.9),('XDWT','NOW','ServiceNow','United States','Technology','Software',1.6),('XDWT','QCOM','Qualcomm','United States','Technology','Semiconductors',1.5),('XDWT','ADBE','Adobe','United States','Technology','Software',1.2)
) AS x(ticker, symbol, name, country, sector, industry, weight) ON x.ticker = e.ticker;
