export const POPULAR_ETFS: { ticker: string; name: string }[] = [
  { ticker: 'SPY', name: 'SPDR S&P 500 ETF Trust' },
  { ticker: 'VOO', name: 'Vanguard S&P 500 ETF' },
  { ticker: 'IVV', name: 'iShares Core S&P 500 ETF' },
  { ticker: 'VTI', name: 'Vanguard Total Stock Market ETF' },
  { ticker: 'QQQ', name: 'Invesco QQQ Trust' },
  { ticker: 'DIA', name: 'SPDR Dow Jones Industrial Average ETF' },
  { ticker: 'IWM', name: 'iShares Russell 2000 ETF' },
  { ticker: 'VV', name: 'Vanguard Large-Cap ETF' },
  { ticker: 'VB', name: 'Vanguard Small-Cap ETF' },
  { ticker: 'VUG', name: 'Vanguard Growth ETF' },
  { ticker: 'VTV', name: 'Vanguard Value ETF' },
  { ticker: 'SCHX', name: 'Schwab U.S. Large-Cap ETF' },
  { ticker: 'SCHD', name: 'Schwab U.S. Dividend Equity ETF' },
  { ticker: 'VIG', name: 'Vanguard Dividend Appreciation ETF' },
  { ticker: 'VYM', name: 'Vanguard High Dividend Yield ETF' },
  { ticker: 'VXUS', name: 'Vanguard Total International Stock ETF' },
  { ticker: 'VEA', name: 'Vanguard FTSE Developed Markets ETF' },
  { ticker: 'VWO', name: 'Vanguard FTSE Emerging Markets ETF' },
  { ticker: 'EEM', name: 'iShares MSCI Emerging Markets ETF' },
  { ticker: 'EFA', name: 'iShares MSCI EAFE ETF' },
  { ticker: 'BND', name: 'Vanguard Total Bond Market ETF' },
  { ticker: 'AGG', name: 'iShares Core US Aggregate Bond ETF' },
  { ticker: 'BNDX', name: 'Vanguard Total International Bond ETF' },
  { ticker: 'TLT', name: 'iShares 20+ Year Treasury Bond ETF' },
  { ticker: 'SHY', name: 'iShares 1-3 Year Treasury Bond ETF' },
  { ticker: 'LQD', name: 'iShares iBoxx Investment Grade Corporate Bond ETF' },
  { ticker: 'HYG', name: 'iShares iBoxx High Yield Corporate Bond ETF' },
  { ticker: 'TIP', name: 'iShares TIPS Bond ETF' },
  { ticker: 'BIL', name: 'SPDR Bloomberg 1-3 Month T-Bill ETF' },
  { ticker: 'XLK', name: 'Technology Select Sector SPDR' },
  { ticker: 'XLF', name: 'Financial Select Sector SPDR' },
  { ticker: 'XLV', name: 'Health Care Select Sector SPDR' },
  { ticker: 'XLE', name: 'Energy Select Sector SPDR' },
  { ticker: 'XLI', name: 'Industrial Select Sector SPDR' },
  { ticker: 'XLP', name: 'Consumer Staples Select Sector SPDR' },
  { ticker: 'XLY', name: 'Consumer Discretionary Select Sector SPDR' },
  { ticker: 'XLU', name: 'Utilities Select Sector SPDR' },
  { ticker: 'XLRE', name: 'Real Estate Select Sector SPDR' },
  { ticker: 'XLB', name: 'Materials Select Sector SPDR' },
  { ticker: 'GLD', name: 'SPDR Gold Shares' },
  { ticker: 'SLV', name: 'iShares Silver Trust' },
  { ticker: 'USO', name: 'United States Oil Fund' },
  { ticker: 'ARKK', name: 'ARK Innovation ETF' },
  { ticker: 'ICLN', name: 'iShares Global Clean Energy ETF' },
  { ticker: 'SMH', name: 'VanEck Semiconductor ETF' },
  { ticker: 'SOXX', name: 'iShares Semiconductor ETF' },
  { ticker: 'VNQ', name: 'Vanguard Real Estate ETF' },
  { ticker: 'IYR', name: 'iShares US Real Estate ETF' },
  { ticker: 'IUSQ', name: 'iShares MSCI ACWI UCITS ETF' },
  { ticker: 'VGVF', name: 'Vanguard FTSE Developed World UCITS ETF' },
  { ticker: 'IUSN', name: 'iShares MSCI World Small Cap UCITS ETF' },
  { ticker: 'NUKL', name: 'VanEck Uranium and Nuclear Technologies UCITS ETF' },
  { ticker: 'EEMA', name: 'iShares MSCI EM Asia UCITS ETF' },
  { ticker: 'XDWT', name: 'iShares MSCI World Information Technology UCITS ETF' },
  { ticker: 'CQQQ', name: 'Invesco China Technology ETF' },
  { ticker: 'ICOM', name: 'iShares Diversified Commodity Swap UCITS ETF' },
];

export const ETF_ALIASES: Record<string, string[]> = {
  'IUSQ': ['msci acwi', 'acwi world'],
  'VGVF': ['ftse developed world', 'developed world'],
  'IUSN': ['msci world small cap', 'world small cap'],
  'SPYD': ['s&p u.s. dividend aristocrats', 'dividend aristocrats'],
  'NUKL': ['uranium and nuclear technologies', 'uranium etf', 'nuclear etf'],
  'ICOM': ['diversified commodities', 'commodities'],
  'EEMA': ['msci em asia', 'emerging asia'],
  'XDWT': ['msci world information technology', 'world tech'],
  'CQQQ': ['msci china tech', 'china technology'],
};
